import { Topic } from './interfaces/topic';

export const Topics: Topic[] = [
    {
        id: "v6gzqlxvb",
        title: "Primer topic",
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet hendrerit purus. Nullam et odio bibendum, malesuada magna at, feugiat quam. Phasellus pharetra ornare nibh et elementum. Praesent ultricies velit a lacus tempor, ut pellentesque massa tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque tincidunt eros a mattis tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec scelerisque tortor nisi, sit amet convallis metus tristique quis. Sed eu nunc iaculis, rhoncus dui cursus, vehicula nisi. Suspendisse scelerisque semper condimentum. In diam nisi, tincidunt quis varius sit amet, vestibulum id elit. Aenean ac luctus libero, eget pulvinar tellus. Praesent et nisi metus. Phasellus mattis a mi eu efficitur. Vestibulum ac pulvinar velit, eu venenatis lectus. Maecenas tincidunt orci at auctor feugiat. Sed ac ipsum vel enim finibus pretium id vel ex. Mauris massa nunc, imperdiet a sapien at, dapibus blandit erat. In eu augue quis dui egestas dignissim. Vivamus quis pulvinar metus. Mauris commodo vulputate libero, ac varius turpis euismod a. Maecenas metus massa, ultrices id massa sit amet, tempor aliquam massa. Nullam volutpat scelerisque tempor. Vestibulum nec augue mauris. Integer dignissim a quam vel pulvinar. Praesent ut eros et lacus sollicitudin consectetur. Fusce non suscipit magna, ac luctus odio. Cras tristique dolor sed eros euismod, at pulvinar dolor suscipit. Aenean magna arcu, varius sed nibh nec, tincidunt semper libero. Ut facilisis iaculis luctus. Praesent iaculis sapien sit amet dignissim ultrices. Donec sollicitudin ac nisl faucibus facilisis. Etiam nec sodales sapien. Sed accumsan efficitur volutpat. Curabitur a orci tincidunt, vulputate magna eget, mattis lacus. Donec vehicula vitae turpis ac semper. Aenean pharetra nunc dolor, vitae laoreet tellus tempor id. Quisque eu turpis elit. In vulputate ac sapien id tristique. Suspendisse dictum est nec sapien sagittis elementum. Curabitur fermentum ultricies augue vitae convallis. Suspendisse interdum fringilla purus id euismod. In hac habitasse platea dictumst. Ut aliquam eget tellus id mattis. Praesent rhoncus turpis quis orci venenatis mattis. Nam purus velit, fermentum id bibendum quis, molestie id nisi. Donec aliquam nulla eu volutpat lobortis. In luctus urna sed congue aliquam. Praesent metus tortor, ultrices nec magna vitae, vulputate gravida urna. In hac habitasse platea dictumst. In sapien purus, mattis eget magna eu, sodales facilisis nunc. Nunc feugiat eget ex sit amet porta. Integer finibus quam sollicitudin, maximus mi eget, congue metus. Etiam diam dolor, mattis mollis molestie vitae, consectetur vehicula justo. Integer lacinia nisl eu elit interdum, ac dignissim tortor ullamcorper. In sodales lacus a arcu laoreet dapibus. Suspendisse potenti.`,
        author: "Toni",
        avatar: "default",
        created: new Date(Date.now()),
        update: new Date(Date.now()),
    },

    {
        id: "dfi3ypai7",
        title: "Segundo topic",
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet hendrerit purus. Nullam et odio bibendum, malesuada magna at, feugiat quam. Phasellus pharetra ornare nibh et elementum. Praesent ultricies velit a lacus tempor, ut pellentesque massa tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque tincidunt eros a mattis tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec scelerisque tortor nisi, sit amet convallis metus tristique quis. Sed eu nunc iaculis, rhoncus dui cursus, vehicula nisi. Suspendisse scelerisque semper condimentum. In diam nisi, tincidunt quis varius sit amet, vestibulum id elit. Aenean ac luctus libero, eget pulvinar tellus. Praesent et nisi metus. Phasellus mattis a mi eu efficitur. Vestibulum ac pulvinar velit, eu venenatis lectus. Maecenas tincidunt orci at auctor feugiat. Sed ac ipsum vel enim finibus pretium id vel ex. Mauris massa nunc, imperdiet a sapien at, dapibus blandit erat. In eu augue quis dui egestas dignissim. Vivamus quis pulvinar metus. Mauris commodo vulputate libero, ac varius turpis euismod a. Maecenas metus massa, ultrices id massa sit amet, tempor aliquam massa. Nullam volutpat scelerisque tempor. Vestibulum nec augue mauris. Integer dignissim a quam vel pulvinar. Praesent ut eros et lacus sollicitudin consectetur. Fusce non suscipit magna, ac luctus odio. Cras tristique dolor sed eros euismod, at pulvinar dolor suscipit. Aenean magna arcu, varius sed nibh nec, tincidunt semper libero. Ut facilisis iaculis luctus. Praesent iaculis sapien sit amet dignissim ultrices. Donec sollicitudin ac nisl faucibus facilisis. Etiam nec sodales sapien. Sed accumsan efficitur volutpat. Curabitur a orci tincidunt, vulputate magna eget, mattis lacus. Donec vehicula vitae turpis ac semper. Aenean pharetra nunc dolor, vitae laoreet tellus tempor id. Quisque eu turpis elit. In vulputate ac sapien id tristique. Suspendisse dictum est nec sapien sagittis elementum. Curabitur fermentum ultricies augue vitae convallis. Suspendisse interdum fringilla purus id euismod. In hac habitasse platea dictumst. Ut aliquam eget tellus id mattis. Praesent rhoncus turpis quis orci venenatis mattis. Nam purus velit, fermentum id bibendum quis, molestie id nisi. Donec aliquam nulla eu volutpat lobortis. In luctus urna sed congue aliquam. Praesent metus tortor, ultrices nec magna vitae, vulputate gravida urna. In hac habitasse platea dictumst. In sapien purus, mattis eget magna eu, sodales facilisis nunc. Nunc feugiat eget ex sit amet porta. Integer finibus quam sollicitudin, maximus mi eget, congue metus. Etiam diam dolor, mattis mollis molestie vitae, consectetur vehicula justo. Integer lacinia nisl eu elit interdum, ac dignissim tortor ullamcorper. In sodales lacus a arcu laoreet dapibus. Suspendisse potenti.`,
        author: "Toni",
        avatar: "default",
        created: new Date(Date.now()),
        update: new Date(Date.now()),
    },


    {
        id: "sup4lx72v",
        title: "Tercero topic",
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet hendrerit purus. Nullam et odio bibendum, malesuada magna at, feugiat quam. Phasellus pharetra ornare nibh et elementum. Praesent ultricies velit a lacus tempor, ut pellentesque massa tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque tincidunt eros a mattis tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec scelerisque tortor nisi, sit amet convallis metus tristique quis. Sed eu nunc iaculis, rhoncus dui cursus, vehicula nisi. Suspendisse scelerisque semper condimentum. In diam nisi, tincidunt quis varius sit amet, vestibulum id elit. Aenean ac luctus libero, eget pulvinar tellus. Praesent et nisi metus. Phasellus mattis a mi eu efficitur. Vestibulum ac pulvinar velit, eu venenatis lectus. Maecenas tincidunt orci at auctor feugiat. Sed ac ipsum vel enim finibus pretium id vel ex. Mauris massa nunc, imperdiet a sapien at, dapibus blandit erat. In eu augue quis dui egestas dignissim. Vivamus quis pulvinar metus. Mauris commodo vulputate libero, ac varius turpis euismod a. Maecenas metus massa, ultrices id massa sit amet, tempor aliquam massa. Nullam volutpat scelerisque tempor. Vestibulum nec augue mauris. Integer dignissim a quam vel pulvinar. Praesent ut eros et lacus sollicitudin consectetur. Fusce non suscipit magna, ac luctus odio. Cras tristique dolor sed eros euismod, at pulvinar dolor suscipit. Aenean magna arcu, varius sed nibh nec, tincidunt semper libero. Ut facilisis iaculis luctus. Praesent iaculis sapien sit amet dignissim ultrices. Donec sollicitudin ac nisl faucibus facilisis. Etiam nec sodales sapien. Sed accumsan efficitur volutpat. Curabitur a orci tincidunt, vulputate magna eget, mattis lacus. Donec vehicula vitae turpis ac semper. Aenean pharetra nunc dolor, vitae laoreet tellus tempor id. Quisque eu turpis elit. In vulputate ac sapien id tristique. Suspendisse dictum est nec sapien sagittis elementum. Curabitur fermentum ultricies augue vitae convallis. Suspendisse interdum fringilla purus id euismod. In hac habitasse platea dictumst. Ut aliquam eget tellus id mattis. Praesent rhoncus turpis quis orci venenatis mattis. Nam purus velit, fermentum id bibendum quis, molestie id nisi. Donec aliquam nulla eu volutpat lobortis. In luctus urna sed congue aliquam. Praesent metus tortor, ultrices nec magna vitae, vulputate gravida urna. In hac habitasse platea dictumst. In sapien purus, mattis eget magna eu, sodales facilisis nunc. Nunc feugiat eget ex sit amet porta. Integer finibus quam sollicitudin, maximus mi eget, congue metus. Etiam diam dolor, mattis mollis molestie vitae, consectetur vehicula justo. Integer lacinia nisl eu elit interdum, ac dignissim tortor ullamcorper. In sodales lacus a arcu laoreet dapibus. Suspendisse potenti.`,
        author: "Toni",
        avatar: "default",
        created: new Date(Date.now()),
        update: new Date(Date.now()),
    },


    {
        id: "c2iokf22",
        title: "Cuarto topic",
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet hendrerit purus. Nullam et odio bibendum, malesuada magna at, feugiat quam. Phasellus pharetra ornare nibh et elementum. Praesent ultricies velit a lacus tempor, ut pellentesque massa tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque tincidunt eros a mattis tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec scelerisque tortor nisi, sit amet convallis metus tristique quis. Sed eu nunc iaculis, rhoncus dui cursus, vehicula nisi. Suspendisse scelerisque semper condimentum. In diam nisi, tincidunt quis varius sit amet, vestibulum id elit. Aenean ac luctus libero, eget pulvinar tellus. Praesent et nisi metus. Phasellus mattis a mi eu efficitur. Vestibulum ac pulvinar velit, eu venenatis lectus. Maecenas tincidunt orci at auctor feugiat. Sed ac ipsum vel enim finibus pretium id vel ex. Mauris massa nunc, imperdiet a sapien at, dapibus blandit erat. In eu augue quis dui egestas dignissim. Vivamus quis pulvinar metus. Mauris commodo vulputate libero, ac varius turpis euismod a. Maecenas metus massa, ultrices id massa sit amet, tempor aliquam massa. Nullam volutpat scelerisque tempor. Vestibulum nec augue mauris. Integer dignissim a quam vel pulvinar. Praesent ut eros et lacus sollicitudin consectetur. Fusce non suscipit magna, ac luctus odio. Cras tristique dolor sed eros euismod, at pulvinar dolor suscipit. Aenean magna arcu, varius sed nibh nec, tincidunt semper libero. Ut facilisis iaculis luctus. Praesent iaculis sapien sit amet dignissim ultrices. Donec sollicitudin ac nisl faucibus facilisis. Etiam nec sodales sapien. Sed accumsan efficitur volutpat. Curabitur a orci tincidunt, vulputate magna eget, mattis lacus. Donec vehicula vitae turpis ac semper. Aenean pharetra nunc dolor, vitae laoreet tellus tempor id. Quisque eu turpis elit. In vulputate ac sapien id tristique. Suspendisse dictum est nec sapien sagittis elementum. Curabitur fermentum ultricies augue vitae convallis. Suspendisse interdum fringilla purus id euismod. In hac habitasse platea dictumst. Ut aliquam eget tellus id mattis. Praesent rhoncus turpis quis orci venenatis mattis. Nam purus velit, fermentum id bibendum quis, molestie id nisi. Donec aliquam nulla eu volutpat lobortis. In luctus urna sed congue aliquam. Praesent metus tortor, ultrices nec magna vitae, vulputate gravida urna. In hac habitasse platea dictumst. In sapien purus, mattis eget magna eu, sodales facilisis nunc. Nunc feugiat eget ex sit amet porta. Integer finibus quam sollicitudin, maximus mi eget, congue metus. Etiam diam dolor, mattis mollis molestie vitae, consectetur vehicula justo. Integer lacinia nisl eu elit interdum, ac dignissim tortor ullamcorper. In sodales lacus a arcu laoreet dapibus. Suspendisse potenti.`,
        author: "Toni",
        avatar: "default",
        created: new Date(Date.now()),
        update: new Date(Date.now()),
    },


];
